CREATE TABLE epics
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(50),
    title       VARCHAR(200)                            NOT NULL,
    description TEXT,
    status      VARCHAR(30)                             NOT NULL,
    start_date  date,
    due_date    date,
    project_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_epics PRIMARY KEY (id)
);

CREATE TABLE epics_aud
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    id          BIGINT  NOT NULL,
    code        VARCHAR(50),
    title       VARCHAR(200),
    description TEXT,
    status      VARCHAR(30),
    start_date  date,
    due_date    date,
    project_id  BIGINT,
    CONSTRAINT pk_epics_aud PRIMARY KEY (rev, id)
);

ALTER TABLE epics
    ADD CONSTRAINT uc_epics_code UNIQUE (code);

CREATE INDEX idx_epic_status ON epics (status);

ALTER TABLE epics_aud
    ADD CONSTRAINT FK_EPICS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE epics
    ADD CONSTRAINT FK_EPICS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

CREATE INDEX idx_epic_project ON epics (project_id);
CREATE TABLE milestone_epics
(
    epic_id      BIGINT NOT NULL,
    milestone_id BIGINT NOT NULL,
    CONSTRAINT pk_milestone_epics PRIMARY KEY (epic_id, milestone_id)
);

CREATE TABLE milestones
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(200)                            NOT NULL,
    description   TEXT,
    status        VARCHAR(30)                             NOT NULL,
    target_date   date                                    NOT NULL,
    achieved_date date,
    project_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_milestones PRIMARY KEY (id)
);

CREATE TABLE milestones_aud
(
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    id            BIGINT  NOT NULL,
    name          VARCHAR(200),
    description   TEXT,
    status        VARCHAR(30),
    target_date   date,
    achieved_date date,
    project_id    BIGINT,
    CONSTRAINT pk_milestones_aud PRIMARY KEY (rev, id)
);

CREATE INDEX idx_milestone_target_date ON milestones (target_date);

ALTER TABLE milestones_aud
    ADD CONSTRAINT FK_MILESTONES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE milestones
    ADD CONSTRAINT FK_MILESTONES_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

CREATE INDEX idx_milestone_project ON milestones (project_id);

ALTER TABLE milestone_epics
    ADD CONSTRAINT fk_milepi_on_epic FOREIGN KEY (epic_id) REFERENCES epics (id);

ALTER TABLE milestone_epics
    ADD CONSTRAINT fk_milepi_on_milestone FOREIGN KEY (milestone_id) REFERENCES milestones (id);