services:
  db:
    image: postgres
    container_name: zenflow-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: zenflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zenflow-network

volumes:
  postgres_data:
    name: zenflow-postgres-data

networks:
  zenflow-network:
    name: zenflow-network
    driver: bridge