CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE permissions_aud
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    id          BIGINT  NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_permissions_aud PRIMARY KEY (rev, id)
);

CREATE TABLE revinfo
(
    id         INTEGER NOT NULL,
    timestamp  BIGINT  NOT NULL,
    username   VARCHAR(255),
    ip_address VARCHAR(255),
    CONSTRAINT pk_revinfo PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE role_permissions_aud
(
    permission_id BIGINT  NOT NULL,
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    role_id       BIGINT  NOT NULL,
    CONSTRAINT pk_role_permissions_aud PRIMARY KEY (permission_id, rev, role_id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE roles_aud
(
    rev     INTEGER NOT NULL,
    revtype SMALLINT,
    id      BIGINT  NOT NULL,
    name    VARCHAR(255),
    CONSTRAINT pk_roles_aud PRIMARY KEY (rev, id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE user_roles_aud
(
    rev     INTEGER NOT NULL,
    revtype SMALLINT,
    role_id BIGINT  NOT NULL,
    user_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_roles_aud PRIMARY KEY (rev, role_id, user_id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    enabled  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_aud
(
    rev      INTEGER NOT NULL,
    revtype  SMALLINT,
    id       BIGINT  NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    enabled  BOOLEAN,
    CONSTRAINT pk_users_aud PRIMARY KEY (rev, id)
);

ALTER TABLE permissions_aud
    ADD CONSTRAINT FK_PERMISSIONS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE roles_aud
    ADD CONSTRAINT FK_ROLES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE users_aud
    ADD CONSTRAINT FK_USERS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE role_permissions_aud
    ADD CONSTRAINT fk_role_permissions_aud_on_rev FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_permission FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles_aud
    ADD CONSTRAINT fk_user_roles_aud_on_rev FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);

-- Per la tabella permissions
ALTER TABLE zenflow.permissions ADD CONSTRAINT permissions_name_unique UNIQUE (name);

-- Per la tabella roles
ALTER TABLE zenflow.roles ADD CONSTRAINT roles_name_unique UNIQUE (name);

-- Per la tabella users
ALTER TABLE zenflow.users ADD CONSTRAINT users_username_unique UNIQUE (username);
ALTER TABLE zenflow.users ADD CONSTRAINT users_email_unique UNIQUE (email);