CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE estimation_votes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id    BIGINT                                  NOT NULL,
    user_story_id BIGINT                                  NOT NULL,
    voter_id      BIGINT                                  NOT NULL,
    story_points  INTEGER,
    reasoning     TEXT,
    CONSTRAINT pk_estimation_votes PRIMARY KEY (id)
);

CREATE TABLE estimation_votes_aud
(
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    id            BIGINT  NOT NULL,
    session_id    BIGINT,
    user_story_id BIGINT,
    voter_id      BIGINT,
    story_points  INTEGER,
    reasoning     TEXT,
    CONSTRAINT pk_estimation_votes_aud PRIMARY KEY (rev, id)
);

CREATE TABLE permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE permissions_aud
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    id          BIGINT  NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_permissions_aud PRIMARY KEY (rev, id)
);

CREATE TABLE planning_poker_sessions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(100)                            NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    project_id     BIGINT                                  NOT NULL,
    facilitator_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_planning_poker_sessions PRIMARY KEY (id)
);

CREATE TABLE planning_poker_sessions_aud
(
    rev            INTEGER NOT NULL,
    revtype        SMALLINT,
    id             BIGINT  NOT NULL,
    name           VARCHAR(100),
    status         VARCHAR(255),
    project_id     BIGINT,
    facilitator_id BIGINT,
    CONSTRAINT pk_planning_poker_sessions_aud PRIMARY KEY (rev, id)
);

CREATE TABLE poker_session_participants
(
    session_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT pk_poker_session_participants PRIMARY KEY (session_id, user_id)
);

CREATE TABLE poker_session_participants_aud
(
    rev        INTEGER NOT NULL,
    revtype    SMALLINT,
    session_id BIGINT  NOT NULL,
    user_id    BIGINT  NOT NULL,
    CONSTRAINT pk_poker_session_participants_aud PRIMARY KEY (rev, session_id, user_id)
);

CREATE TABLE project_team_members
(
    project_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT pk_project_team_members PRIMARY KEY (project_id, user_id)
);

CREATE TABLE project_team_members_aud
(
    project_id BIGINT  NOT NULL,
    rev        INTEGER NOT NULL,
    revtype    SMALLINT,
    user_id    BIGINT  NOT NULL,
    CONSTRAINT pk_project_team_members_aud PRIMARY KEY (project_id, rev, user_id)
);

CREATE TABLE projects
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(100)                            NOT NULL,
    description            VARCHAR(500),
    status                 VARCHAR(255)                            NOT NULL,
    type                   VARCHAR(255)                            NOT NULL,
    start_date             date,
    end_date               date,
    owner_id               BIGINT                                  NOT NULL,
    total_story_points     INTEGER,
    completed_story_points INTEGER,
    team_velocity          DOUBLE PRECISION,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE projects_aud
(
    rev                    INTEGER NOT NULL,
    revtype                SMALLINT,
    id                     BIGINT  NOT NULL,
    name                   VARCHAR(100),
    description            VARCHAR(500),
    status                 VARCHAR(255),
    type                   VARCHAR(255),
    start_date             date,
    end_date               date,
    owner_id               BIGINT,
    total_story_points     INTEGER,
    completed_story_points INTEGER,
    team_velocity          DOUBLE PRECISION,
    CONSTRAINT pk_projects_aud PRIMARY KEY (rev, id)
);

CREATE TABLE revinfo
(
    id         INTEGER NOT NULL,
    timestamp  BIGINT  NOT NULL,
    username   VARCHAR(255),
    ip_address VARCHAR(255),
    CONSTRAINT pk_revinfo PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE role_permissions_aud
(
    permission_id BIGINT  NOT NULL,
    rev           INTEGER NOT NULL,
    revtype       SMALLINT,
    role_id       BIGINT  NOT NULL,
    CONSTRAINT pk_role_permissions_aud PRIMARY KEY (permission_id, rev, role_id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE roles_aud
(
    rev     INTEGER NOT NULL,
    revtype SMALLINT,
    id      BIGINT  NOT NULL,
    name    VARCHAR(255),
    CONSTRAINT pk_roles_aud PRIMARY KEY (rev, id)
);

CREATE TABLE sprints
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(100)                            NOT NULL,
    goal                   VARCHAR(500),
    start_date             date                                    NOT NULL,
    end_date               date                                    NOT NULL,
    status                 VARCHAR(255)                            NOT NULL,
    project_id             BIGINT                                  NOT NULL,
    planned_story_points   INTEGER,
    completed_story_points INTEGER,
    sprint_velocity        DOUBLE PRECISION,
    CONSTRAINT pk_sprints PRIMARY KEY (id)
);

CREATE TABLE sprints_aud
(
    rev                    INTEGER NOT NULL,
    revtype                SMALLINT,
    id                     BIGINT  NOT NULL,
    name                   VARCHAR(100),
    goal                   VARCHAR(500),
    start_date             date,
    end_date               date,
    status                 VARCHAR(255),
    project_id             BIGINT,
    planned_story_points   INTEGER,
    completed_story_points INTEGER,
    sprint_velocity        DOUBLE PRECISION,
    CONSTRAINT pk_sprints_aud PRIMARY KEY (rev, id)
);

CREATE TABLE tasks
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(200)                            NOT NULL,
    description     TEXT,
    status          VARCHAR(255)                            NOT NULL,
    estimated_hours DOUBLE PRECISION,
    actual_hours    DOUBLE PRECISION,
    user_story_id   BIGINT                                  NOT NULL,
    assigned_to     BIGINT,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE tasks_aud
(
    rev             INTEGER NOT NULL,
    revtype         SMALLINT,
    id              BIGINT  NOT NULL,
    title           VARCHAR(200),
    description     TEXT,
    status          VARCHAR(255),
    estimated_hours DOUBLE PRECISION,
    actual_hours    DOUBLE PRECISION,
    user_story_id   BIGINT,
    assigned_to     BIGINT,
    CONSTRAINT pk_tasks_aud PRIMARY KEY (rev, id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE user_roles_aud
(
    rev     INTEGER NOT NULL,
    revtype SMALLINT,
    role_id BIGINT  NOT NULL,
    user_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_roles_aud PRIMARY KEY (rev, role_id, user_id)
);

CREATE TABLE user_stories
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                VARCHAR(200)                            NOT NULL,
    description          TEXT,
    acceptance_criteria  TEXT,
    status               VARCHAR(255)                            NOT NULL,
    priority             VARCHAR(255)                            NOT NULL,
    story_points         INTEGER,
    business_value       INTEGER,
    project_id           BIGINT                                  NOT NULL,
    sprint_id            BIGINT,
    assigned_to          BIGINT,
    optimistic_estimate  DOUBLE PRECISION,
    pessimistic_estimate DOUBLE PRECISION,
    most_likely_estimate DOUBLE PRECISION,
    pert_estimate        DOUBLE PRECISION,
    CONSTRAINT pk_user_stories PRIMARY KEY (id)
);

CREATE TABLE user_stories_aud
(
    rev                  INTEGER NOT NULL,
    revtype              SMALLINT,
    id                   BIGINT  NOT NULL,
    title                VARCHAR(200),
    description          TEXT,
    acceptance_criteria  TEXT,
    status               VARCHAR(255),
    priority             VARCHAR(255),
    story_points         INTEGER,
    business_value       INTEGER,
    project_id           BIGINT,
    sprint_id            BIGINT,
    assigned_to          BIGINT,
    optimistic_estimate  DOUBLE PRECISION,
    pessimistic_estimate DOUBLE PRECISION,
    most_likely_estimate DOUBLE PRECISION,
    pert_estimate        DOUBLE PRECISION,
    CONSTRAINT pk_user_stories_aud PRIMARY KEY (rev, id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    enabled  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_aud
(
    rev      INTEGER NOT NULL,
    revtype  SMALLINT,
    id       BIGINT  NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    enabled  BOOLEAN,
    CONSTRAINT pk_users_aud PRIMARY KEY (rev, id)
);

ALTER TABLE estimation_votes_aud
    ADD CONSTRAINT FK_ESTIMATION_VOTES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE estimation_votes
    ADD CONSTRAINT FK_ESTIMATION_VOTES_ON_SESSION FOREIGN KEY (session_id) REFERENCES planning_poker_sessions (id);

ALTER TABLE estimation_votes
    ADD CONSTRAINT FK_ESTIMATION_VOTES_ON_USER_STORY FOREIGN KEY (user_story_id) REFERENCES user_stories (id);

ALTER TABLE estimation_votes
    ADD CONSTRAINT FK_ESTIMATION_VOTES_ON_VOTER FOREIGN KEY (voter_id) REFERENCES users (id);

ALTER TABLE permissions_aud
    ADD CONSTRAINT FK_PERMISSIONS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE planning_poker_sessions_aud
    ADD CONSTRAINT FK_PLANNING_POKER_SESSIONS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE planning_poker_sessions
    ADD CONSTRAINT FK_PLANNING_POKER_SESSIONS_ON_FACILITATOR FOREIGN KEY (facilitator_id) REFERENCES users (id);

ALTER TABLE planning_poker_sessions
    ADD CONSTRAINT FK_PLANNING_POKER_SESSIONS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE projects_aud
    ADD CONSTRAINT FK_PROJECTS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE roles_aud
    ADD CONSTRAINT FK_ROLES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE sprints_aud
    ADD CONSTRAINT FK_SPRINTS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE sprints
    ADD CONSTRAINT FK_SPRINTS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE tasks_aud
    ADD CONSTRAINT FK_TASKS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_ASSIGNED_TO FOREIGN KEY (assigned_to) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_USER_STORY FOREIGN KEY (user_story_id) REFERENCES user_stories (id);

ALTER TABLE users_aud
    ADD CONSTRAINT FK_USERS_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE user_stories_aud
    ADD CONSTRAINT FK_USER_STORIES_AUD_ON_REV FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE user_stories
    ADD CONSTRAINT FK_USER_STORIES_ON_ASSIGNED_TO FOREIGN KEY (assigned_to) REFERENCES users (id);

ALTER TABLE user_stories
    ADD CONSTRAINT FK_USER_STORIES_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE user_stories
    ADD CONSTRAINT FK_USER_STORIES_ON_SPRINT FOREIGN KEY (sprint_id) REFERENCES sprints (id);

ALTER TABLE poker_session_participants_aud
    ADD CONSTRAINT fk_poker_session_participants_aud_on_rev FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE poker_session_participants
    ADD CONSTRAINT fk_poksespar_on_planning_poker_session FOREIGN KEY (session_id) REFERENCES planning_poker_sessions (id);

ALTER TABLE poker_session_participants
    ADD CONSTRAINT fk_poksespar_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE project_team_members_aud
    ADD CONSTRAINT fk_project_team_members_aud_on_rev FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE project_team_members
    ADD CONSTRAINT fk_proteamem_on_project FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE project_team_members
    ADD CONSTRAINT fk_proteamem_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE role_permissions_aud
    ADD CONSTRAINT fk_role_permissions_aud_on_rev FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_permission FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles_aud
    ADD CONSTRAINT fk_user_roles_aud_on_rev FOREIGN KEY (rev) REFERENCES revinfo (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);

-- Per la tabella permissions
ALTER TABLE zenflow.permissions ADD CONSTRAINT permissions_name_unique UNIQUE (name);

-- Per la tabella roles
ALTER TABLE zenflow.roles ADD CONSTRAINT roles_name_unique UNIQUE (name);

-- Per la tabella users
ALTER TABLE zenflow.users ADD CONSTRAINT users_username_unique UNIQUE (username);
ALTER TABLE zenflow.users ADD CONSTRAINT users_email_unique UNIQUE (email);